apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  namespace: mongodb-namespace
spec:
    rules:
    - host: mongodb.fabienganderatz.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mongodb-express-service
                port:
                  number: 8081
    tls:
    - hosts:
      - mongodb.fabienganderatz.com
      secretName: myapp-secret-tls
