apiVersion: v1
kind: Namespace
metadata:
  name: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongodb-ingress
  namespace: mongodb
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Cluster-issuer Change
spec:
  tls:
  - secretName: mongodb-tls-cert
    hosts:
    - mongodb.fabienganderatz.com
  rules:
  - host: mongodb.fabienganderatz.com
    http:
      paths:
      - path: /
        backend:
          serviceName: mongodb-service
          servicePort: 27017
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongodb-tls-cert
  namespace: mongodb
spec:
  secretName: mongodb-tls-cert
  issuerRef:
    name: letsencrypt-prod
  commonName: mongodb.fabienganderatz.com
  dnsNames:
  - mongodb.fabienganderatz.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - mongodb.fabienganderatz.com