---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express-deployment
  namespace: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express

        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongo-root-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        ports:
        - name: mongo-express
          containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: mongo-database
spec:
  selector:
    app: mongo-express
  type: ClusterIP
  ports:
    - name: mongo-express
      port: 8081
      protocol: TCP
      targetPort: 8081
      #nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
  namespace: mongo-database
  annotations:
    kubernetes.io/ingress.class: "nginx"    
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # Cluster-issuer Change
spec:
  rules:
  - host: "mongodb.fabienganderatz.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mongodb-svc 
            port:
              number: 80
  tls:
  - hosts:
    - mongodb.fabienganderatz.com
    secretName: mongodb-tls-secret              
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mongo-express-cert
  namespace: mongo-database
spec:
  secretName: mongodb-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - mongodb.fabienganderatz.com
